version: '3.3'
services:

  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    restart: always
    volumes:
      - static_value:/foodgram/backend_static/
      - media_value:/foodgram/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/foodgram/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/foodgram/backend_static/
      - media_value:/foodgram/backend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - frontend


volumes:
  postgres_data:
  static_value:
  media_value:
