# Generated by Django 4.0.4 on 2022-05-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тэга')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес тэга')),
                ('color', models.CharField(default='2c3cba', max_length=7, verbose_name='Цвет(HEX)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
